# Generated by Django 2.2.5 on 2019-12-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('besfit', '0002_auto_20191213_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('multiple_answers', 'multiple_answers'), ('single_answer', 'one_answer'), ('true_false', 'true_false')], max_length=50)),
                ('category', models.CharField(choices=[('english', 'english'), ('urdu', 'urdu'), ('math', 'math')], max_length=100)),
                ('correct_answer1', models.IntegerField()),
                ('correct_answer2', models.IntegerField()),
                ('correct_answer3', models.IntegerField()),
                ('option1', models.IntegerField()),
                ('option2', models.IntegerField()),
                ('option3', models.IntegerField()),
                ('option4', models.IntegerField()),
            ],
        ),
    ]
