# Generated by Django 2.2.5 on 2019-12-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('besfit', '0003_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
