# Generated by Django 2.2.5 on 2019-12-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('besfit', '0004_questions_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(default='', max_length=200),
        ),
    ]
