# Generated by Django 2.2.5 on 2019-12-19 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('besfit', '0006_auto_20191218_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='correct_answer2',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='correct_answer3',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question_type',
        ),
    ]
