# Generated by Django 2.2.5 on 2019-12-19 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('besfit', '0007_auto_20191218_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='correct_answer1',
            new_name='correct_answer',
        ),
    ]
